<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\ToDoApp.Application\ToDoApp.Application.csproj" />
    <ProjectReference Include="..\..\Domain\ToDoApp.Domain\ToDoApp.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ToDoApp.Infrastructure\ToDoApp.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Common\Shared.Common\Shared.Common.csproj" />
  </ItemGroup>

</Project>
